---
on:
  push:
    branches:
      - '*'
    tags:
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: l.gcr.io/google/bazel:latest
      volumes:
        - ${{ github.workspace }}:/work
      options: |
        --workdir /work
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v2
      - name: Checkout sub repo
        uses: actions/checkout@v2
        with:
          # TODO(jseo): Make a dockerfile to contain git > 2.8
          repository: jonghoonseo/Awesome-CV
          path: Awesome-CV
      - name: Build
        run: |
          bazel build resume
          cp "$(realpath bazel-bin/resume.pdf)" ./resume_jonghoonseo.pdf
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: resume_jonghoonseo.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
